




name: CI
env:
        project: phpinfo-2
        swarm_compose: etc/swarm/manifests/${project}.yaml
        kube_compose: etc/kubernetes/manifests/${project}.yaml
on:
        push:
                branches:
                -
                        docker
jobs:
        docker:
                runs-on: ubuntu-18.04
                steps:
                -
                        name: checkout
                        uses: actions/checkout@v2
                -
                        name: test
                        run: docker build -t test .
                -
                        name: docker run
                        run: docker run -d --name test test
                -
                        name: wait Up
                        run: |
                                while true; do
                                        sleep 10;
                                        docker exec test ps | grep 'php -f index.php' && break
                                done;
                                while true; do
                                        sleep 10;
                                        docker logs test 2>& 1 | grep 'PHP .* Development Server started' && break
                                done;
        swarm:
                runs-on: ubuntu-18.04
                steps:
                -
                        name: checkout
                        uses: actions/checkout@v2
                -
                        name: test
                        run: docker build -t ganimedescolomar/phpinfo-2:testing .
                -
                        name: docker swarm init
                        run: docker swarm init --advertise-addr lo
                -
                        name: sed
                        run: sed -i /image:/s/latest/testing/ ${swarm_compose}
                -
                        name: sed2
                        run: sed -i /node.role/s/worker/manager/ ${swarm_compose}
                        # Deploy in Openshift
                        # oc apply -f ${compose}
                -
                        name: deploy
                        run: docker stack deploy -c ${swarm_compose} ${project}
                -
                        name: docker service ls
                        run: |
                                while true; do
                                        sleep 10;
                                        docker service ls | grep "${project}.*\([0-9]\)/\1" && break
                                done;
                -
                        name: docker service logs
                        run: |
                                while true; do
                                        sleep 10;
                                        docker service logs ${project}_${project} 2>& 1 | grep 'PHP .* Development Server started' && break
                                done;
        kubernetes:
                runs-on: ubuntu-18.04
                steps:
                -
                        name: checkout
                        uses: actions/checkout@v2
                -
                        name: test
                        run: docker build -t ganimedescolomar/phpinfo-2:testing .
                -
                        name: install kubernetes
                        run: |
                                sudo apt-get update
                                sudo apt-get install -y docker.io
                                sudo systemctl enable --now docker
                                curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
                                echo deb http://apt.kubernetes.io/ kubernetes-xenial main | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
                                sudo apt-get update
                                sudo apt-get install -y --allow-downgrades kubelet-1.18.14-00 kubeadm-1.18.14-00 kubectl=1.18.14-00
                                sudo systemctl enable --now kubelet
                -
                        name: init kubernetes
                        run: |
                                ip_leader=$( ip r | grep default | awk '{ print $9 }' )
                                echo ${ip_leader} kube-apiserver | sudo tee -a /etc/hosts
                                sudo swapoff --all
                                sudo kubeadm init --upload-certs --control-plane-endpoint kube-apiserver --pod-network-cidr 192.168.0.0/16 --ignore-preflight-errors all
                -
                        name: create network
                        run: sudo kubectl apply -f https://docs.projectcalico.org/v3.17/manifests/calico.yaml
                -
                        name: credentials
                        run: |
                                mkdir -p ${HOME}/.kube
                                sudo cp /etc/kubernetes/admin.conf ${HOME}/.kube/config
                                sudo chown -R $( id -u ):( id -g ) ${HOME}/.kube
                -
                        name: edit kube_compose
                        run: |
                                sed -i /image:/s/latest/testing/ ${kube_compose}
                                sed -i /imagePullPolicy/s/Always/Never/ ${kube_compose}
                -
                        name: wait cluster
                        run: |
                                while true; do
                                        kubectl get node | grep Ready | grep -v NotReady && break;
                                        sleep 10;
                                done;
                -
                        name: clean config
                        run: |
                                sudo sed -i /kube-apiserver/d /etc/hosts
                                sudo sed -i /127.0.0.1.*localhost/s/$/' 'kube-apiserver/ /etc/hosts
                -
                        name: enable master
                        run: |
                                master=$( kubectl get node | grep master | awk '{ print $1 }' )
                                kubectl taint node ${master} node-role.kubernetes.io/master:NoSchedule-
                -
                        name: deploy
                        run: kubectl apply -f ${kube_compose}
                -
                        name: kubectl get deploy
                        run: |
                                while true; do
                                        sleep 10;
                                        kubectl get deploy | grep "${project}.*\([0-9]\)/\1" && break
                                done;
                -
                        name: kubectl logs deploy
                        run: |
                                while true; do
                                        sleep 10;
                                        kubectl logs deploy/${project} 2>& 1 | grep 'PHP .* Development Server .* started' && break
                                done;









